# -*- coding: utf-8 -*-
"""employee performance level

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W0Mpy2lJGD3GzCY09q4lPAL-0TDNI7Bn
"""

def calculate_bonus(name, salary, projects, performance):
  if performance >=90:
    performance_level = "Excellent"
  elif performance >= 80:
    performance_level = "Very Good"
  elif performance >= 70:
    performance_level = "Good"
  else:
    performance_level = "Do better"

  #Bonus

  if performance_level == "Excellent" and projects >= 3:
    bonus_percent = 20
  elif performance_level == " Very Good" and projects >= 3:
    bonus_percent = 15
  elif performance_level == "Good" and projects >= 2:
    bonus_percent = 10
  else:
    bonus_percent = 0

  bonus = salary * bonus_percent / 100
  total_salary = salary + bonus

  print("Employee: ", name)
  print("Performance: ", performance_level)
  print("Projects: ", projects)
  print("Bonus: ", int(bonus))
  print("Total Salary", int(total_salary))

calculate_bonus("Ali", 75000, 3, 94)